### ISSUE TITLE
main.go not compatible with 0.9 influx lib (undefined: client.Series error)

### ISSUE THREAD

**Issue by BarthV** [novaquark/sysinfo_influxdb#27]
The InfluxDB go lib have moved forward : 
- When using 0.9-rc5 or current master we now face :
```bash
> go build
./main.go:251: undefined: client.Series
./main.go:276: undefined: client.Series
./main.go:286: undefined: client.Series
./main.go:344: undefined: client.Series
./main.go:346: undefined: client.Series
./main.go:364: undefined: client.Series
./main.go:381: undefined: client.Series
./main.go:399: undefined: client.Series
./main.go:417: undefined: client.Series
./main.go:417: too many errors
```

```influxClient -> client.Series``` have been deprecated, and we need to update this project's master to build it back :).

I've made a temporary fix to pin back 0.8.8 lib inside the project (building is working on this branch) : 
- https://github.com/BarthV/sysinfo_influxdb/tree/pin0.8.8

I can PR this branch just the time needed to update the whole code to 0.9 lib.

thanks

**Comment by nemunaire** [comment]
I think there are a huge amount of changes relative to the new InfluxDB design:

* the DB name is now part of JSON series;
* we should add an optional argument for `retentionPolicy`;
* points are now a hash-table: no need for giving column names anymore;
* find how we can use tags.

-----

As a workaround for versions under 0.9, you should manually checkout the `0.8` branch of the InfluxDB repository:

    cd $GOPATH/src/github.com/influxdb/
    git checkout 0.8

And then build `sysinfo_influxdb`.

I don't find how to specify a tag or branch to the go import path :-(

**Comment by BarthV** [comment]
@nemunaire : Do you have some time to work on this ?

**Comment by nemunaire** [comment]
Yes, I'm working on it ;-)

A revision for 0.9 should arrive by the end of the day.

**Comment by nemunaire** [comment]
The `develop` branch now contains a revision working with the 0.9 branch.

Consult the commit message (cf069e9f845ecf3688f7b61b70d197b273cd7850) for more details.

Don't hesitate to comment ;-)

One more thing to do is replacing hostname/port parameters by an URL.

**Comment by salsa-dev** [comment]
Hi,
I' m using the latest develop branch and recieve an error while building:

`# github.com/novaquark/sysinfo_influxdb`
`./main.go:252: undefined: client.Write`

I'm new to Go and the build process. Just in case here are the steps I prepare for a build:

`export GOPATH=$HOME/DEV/gocode`
`export GOROOT=$HOME/DEV/go`
`export PATH=$PATH:$HOME/DEV/go/bin`

`wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz`
`tar zxvf go1.4.2.linux-amd64.tar.gz `
`mkdir -p $HOME/gocode/src/github.com/novaquark/`
`cd gocode/src/github.com/novaquark/`
`git clone https://github.com/novaquark/sysinfo_influxdb.git`
`cd sysinfo_influxdb/`
`git checkout develop`
`go get`

Please comment.

**Comment by nemunaire** [comment]
The InfluxDB API has changed since the release candidate I use to develop this new version.

@salsa-dev: I just push a new commit on `develop` to fix that.

**Comment by yaryarrr** [comment]
I'm still having some issues:

```
[root@localhost sysinfo_influxdb]# go get
# github.com/novaquark/sysinfo_influxdb
./main.go:29: undefined: client.Series
```

when i switch to develop branch:

```
[root@localhost sysinfo_influxdb]# go get
# github.com/novaquark/sysinfo_influxdb
./main.go:278: serie.Name undefined (type *client.Point has no field or method Name)
./main.go:343: unknown client.Point field 'Name' in struct literal
./main.go:367: unknown client.Point field 'Name' in struct literal
./main.go:396: unknown client.Point field 'Name' in struct literal
./main.go:417: unknown client.Point field 'Name' in struct literal
./main.go:436: unknown client.Point field 'Name' in struct literal
./main.go:453: unknown client.Point field 'Name' in struct literal
./main.go:498: unknown client.Point field 'Name' in struct literal
./main.go:546: unknown client.Point field 'Name' in struct literal
./main.go:600: unknown client.Point field 'Name' in struct literal
./main.go:600: too many errors
```

any recommendations? thanks in advance!

**Comment by nemunaire** [comment]
`master` branch (version/tag 0.5.4) is now up to date and work with InfluxDB 0.9 :)
